export const ROUTES = {
	login: 'login',
	dashboard: 'dashboard',
	manageParticipant: 'manageParticipant',
	registerParticipant: 'registerParticipant',
	bulkImport: 'bulkImport',
	approveParticipants: 'approveParticipants',
	viewParticipants: 'viewParticipants',
	manageStaff: 'manageStaff',
	registerStaff: 'registerStaff',
	viewStaff: 'viewStaff',
	staffDashboard: 'staffDashboard',
	manageQuestions: 'manageQuestions',
	uploadQuestions: 'uploadQuestions',
	manageChecklist: 'manageChecklist',
	checklistView: 'checklistView',
	checklistResults: 'checklistResults',
	uploadChecklist: 'uploadChecklist',
	viewEditDeleteChecklist: 'viewEditDeleteChecklist',
	checklistSettings: 'checklistSettings',
	preTest: 'preTest',
	postTest: 'postTest',
	testSettings: 'testSettings',
	testInterface: 'testInterface',
	testResults: 'testResults',
	questionPoolManagement: 'questionPoolManagement',
	accessControlManagement: 'accessControlManagement',
	resultsAnalytics: 'resultsAnalytics',
	importResults: 'importResults',
	bulkImportResults: 'bulkImportResults',
	resultView: 'resultView',
	resultAnalysis: 'resultAnalysis',
	resultSettings: 'resultSettings',
	certificateManagement: 'certificateManagement',
	comprehensiveResults: 'comprehensiveResults',
	createCourse: 'createCourse',
	viewCourses: 'viewCourses',
	editCourse: 'editCourse',
	attendanceMonitoring: 'attendanceMonitoring',
} as const;

export type RouteKey = keyof typeof ROUTES;
