// Count the original participants from the data you provided
const originalParticipantData = `ABDUL RAHMAN BIN MOHAMAD BADARUDDIN PASS PASS PASS PASS PASS
AHMAD ZAKI ISAMUDDIN BIN MOHAMAD PASS PASS PASS PASS PASS
ALVIN DULAMIT PASS PASS PASS PASS PASS
AMANDA BULAN SIGAR PASS PASS PASS PASS PASS
AMIR LUQMAN BIN MISKANI PASS PASS PASS PASS PASS
ANGELINA RURAN SIGAR PASS PASS PASS PASS PASS
AWANGKU MOHAMMAD ZULFAZLI BIN AWANGKU ABDUL RAZAK PASS PASS PASS PASS PASS
CATHERINE JOHN PASS PASS PASS PASS PASS
CHRISTINA PADIN PASS PASS PASS PASS PASS
CHRISTINE KOW CHONG LI PASS PASS PASS PASS PASS
ELSIE ANAK BITI PASS PASS PASS PASS PASS
EMILY AKUP PASS PASS PASS PASS PASS
FAIRYLICIA BRAIM PASS PASS PASS PASS PASS
FARIDAH BINTI KUNAS PASS PASS PASS PASS PASS
FIZRA IVY WAS PASS PASS PASS PASS FAIL
GRACE NYURA ANAK JAMBAI PASS PASS PASS PASS PASS
GRACE RURAN NGILO FAIL FAIL PASS PASS FAIL
IMANUEL G. KORO PASS PASS PASS PASS PASS
JANIZA BINTI BUJANG PASS PASS PASS PASS PASS
JOHARI BIN EPIN PASS PASS PASS PASS PASS
KAMARIAH BINTI MOHAMAD ALI PASS PASS PASS PASS PASS
MANSUR BIN MURNI FAIL FAIL PASS PASS FAIL
MARZUKI RAJANG FAIL FAIL PASS PASS FAIL
METHDIOUSE ANAK SILAN PASS PASS PASS PASS PASS
MISRAWATI MA AMAN PASS PASS PASS PASS PASS
MOHAMAD FARIZZUL BIN JAYA PASS PASS PASS PASS PASS
MOHAMMAD ANNAS BIN BOING PASS PASS PASS PASS PASS
MUHD ZAINUL 'IZZAT BIN ZAINUDIN PASS PASS PASS PASS PASS
MUHSINAH BINTI ABDUL SHOMAD PASS PASS PASS PASS PASS
MYRA ATHIRA BINTI OMAR PASS PASS PASS PASS PASS
NADHIRAH BINTI MOHD HANAFIAH PASS PASS PASS PASS PASS
NAZURAH BINTI ABDUL LATIP PASS PASS PASS PASS PASS
NOR BAIZURAH BINTI MASLIM FAIL FAIL PASS PASS FAIL
NORFARAIN BINTI SARBINI@SALDAN PASS PASS PASS PASS PASS
NORLINA BINTI ALI PASS PASS PASS PASS PASS
NORSHELA BINTI YUSUF PASS PASS PASS PASS PASS
NUR AMANDA BELINDA JARUT PASS PASS PASS PASS PASS
NURITA BINTI HANTIN PASS PASS PASS PASS PASS
NURIZANIE BINTI SANEH PASS PASS PASS PASS FAIL
NURMASLIANA BINTI ISMAIL PASS PASS PASS PASS FAIL
NURUL HAZWANIE ABDULLAH PASS PASS PASS PASS PASS
PRISCA ANAK RUE PASS PASS PASS PASS PASS
RAJAMI BIN ABDUL HASHIM FAIL FAIL PASS PASS FAIL
RAZAMAH BINTI DULLAH PASS PASS PASS PASS PASS
RURAN SAUL PASS PASS PASS PASS PASS
SA'DI BIN USOP FAIL FAIL PASS PASS FAIL
SAUDAAH BINTI IDANG PASS PASS PASS PASS PASS
SHAHIRUL AQMAL BIN SHAHEEDAN PASS PASS PASS PASS PASS
SHAHRULNIZAM BIN IBRAHIM PASS PASS PASS PASS PASS
SHIRLEY SEBELT PASS PASS PASS PASS PASS
SITI KHAIRUNISA BINTI ZALEK PASS PASS PASS PASS PASS
SUHARMIE BIN SULAIMAN PASS PASS PASS PASS PASS
TRACY JONAS PASS PASS PASS PASS PASS
VOON KING FATT PASS PASS PASS PASS PASS
WENDY CHANDI ANAK SAMPURAI PASS PASS PASS PASS PASS
YONG ZILING PASS PASS PASS PASS PASS`;

const lines = originalParticipantData.trim().split('\n');
const participantCount = lines.length;

console.log('🔍 Counting original participants...');
console.log(`✅ Original participant count: ${participantCount}`);

console.log('\n📋 First 10 participants:');
lines.slice(0, 10).forEach((line, index) => {
  const parts = line.split(' ');
  const name = parts.slice(0, -5).join(' '); // Everything except last 5 results
  console.log(`${index + 1}. ${name}`);
});

console.log('\n📋 Last 10 participants:');
lines.slice(-10).forEach((line, index) => {
  const parts = line.split(' ');
  const name = parts.slice(0, -5).join(' '); // Everything except last 5 results
  console.log(`${participantCount - 9 + index}. ${name}`);
});

console.log('\n🔍 Checking for participants with FAIL results:');
const failParticipants = [];
lines.forEach((line, index) => {
  if (line.includes('FAIL')) {
    const parts = line.split(' ');
    const name = parts.slice(0, -5).join(' ');
    const results = parts.slice(-5);
    failParticipants.push({ name, results, lineNumber: index + 1 });
  }
});

console.log(`\n❌ Participants with FAIL results: ${failParticipants.length}`);
failParticipants.forEach(participant => {
  console.log(`   ${participant.lineNumber}. ${participant.name}: ${participant.results.join(', ')}`);
});

console.log('\n💡 Expected database records:');
console.log(`   Total participants: ${participantCount}`);
console.log(`   Total assessment records: ${participantCount * 5} (5 assessments per participant)`);
console.log(`   Current database shows: 50 participants`);
console.log(`   Missing: ${participantCount - 50} participants`);


